site_name: ZLDF的个人主页
repo_url: https://github.com/ZhengliangDuanfang/hmpg_mkdocs
repo_name: hmpg_mkdocs

theme: 
  name: material

  font:
    text: 'Noto Serif SC'
    code: 'Noto Sans Mono'

  # logo: 'img/icon.png'
  logo: 'img/logo-v0.2.svg'
  favicon: 'img/logo-v0.2.svg'

  features:
    - navigation.tabs

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

nav:
  - 主页: 'index.md'
  - 本科课程: 
    - 说明: '本科课程/index.md'
    - ZJU大物实验课程资源目录: '本科课程/phylab-navigator.md' 
  - 杂项: 
    - 搭建记录: '杂项/building.md'
    - LaTeX笔记: '杂项/latex.md'
    - 使用RustDesk和自建服务器实现远程桌面控制: '杂项/rustdesk.md'
  - 兴趣:
    - 随想与摘抄: '兴趣/opinion.md'
    - 译鲍照《从拜陵登京岘》诗: '兴趣/rclt.md'
    - 清真年表: '兴趣/清真年表.md'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  # generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhengliangDuanfang
      name: My GitHub
