site_name: ZLDF的个人主页
repo_url: https://github.com/ZhengliangDuanfang/hmpg_mkdocs
repo_name: hmpg_mkdocs

theme: 
  name: material

  font:
    text: 'Noto Serif SC'
    code: 'Noto Sans Mono'

  logo: 'img/icon.png'
  favicon: 'img/icon.png'

  features:
    - navigation.tabs

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

nav:
  - 主页: 'index.md'
  - 杂项: 
    - 搭建记录: '杂项/building.md'
    - LaTeX笔记: '杂项/latex.md'
  - 兴趣:
    - 随想与摘抄: '兴趣/opinion.md'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  # generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhengliangDuanfang
      name: My GitHub
