site_name: ZLDF的个人主页

theme: 
  name: material

  font:
    text: 'Noto Serif SC'
    code: 'Noto Sans Mono'

  logo: 'img/icon.png'
  favicon: 'img/icon.png'

  features:
    - navigation.tabs

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - 主页: 'index.md'
  - 杂项: 
    - 搭建记录: 'building.md'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences