site_name: ZLDF的个人主页
repo_url: https://github.com/ZhengliangDuanfang/hmpg_mkdocs
repo_name: hmpg_mkdocs

theme: 
  name: material
  custom_dir: custom_theme/

  font:
    text: 'Noto Serif SC'
    code: 'Noto Sans Mono'

  logo: 'img/logo-v2.2.png'
  favicon: 'img/logo-v2.2.png'

  features:
    - navigation.tabs

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

nav:
  - 主页: 'index.md'
  - 本科课程: 
    - 说明: 'courses/index.md'
    - ZJU大物实验课程资源目录: 'courses/phylab-navigator.md' 
    - SRTP笔记: 'courses/SRTPnote.md'
    - RISC-V递归的两种实现: 'courses/cod2_16.md'
    - 数据库系统笔记: 
      - MySQL笔记: 'courses/mysql.md'
      - JDBC笔记: 'courses/jdbc.md'
      - 范式与范化笔记: 'courses/norm.md'
    - 计算机网络笔记: "https://zhengliangduanfang.github.io/T-ComputerNetworks/"
  - 工作流:
    - 工作流记录: 'workflow/index.md'
    - Linux笔记: 'workflow/linux.md' 
    - Docker笔记: 'workflow/docker.md'
    - Git笔记: 'workflow/git.md'
    - LaTeX笔记: 'workflow/latex.md'
  - 杂项: 
    - 本站搭建记录: 'misc/building.md'
    - 使用RustDesk和自建服务器实现远程桌面控制: 'misc/rustdesk.md'
    - 不成篇杂项: 'misc/others.md'
  - 兴趣:
    - 随想与摘抄: 'hobby/opinion.md'
    - 译鲍照《从拜陵登京岘》诗: 'hobby/rclt.md'
    - 清真年表: 'hobby/zby_chrono.md'



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra:
  # generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhengliangDuanfang
      name: My GitHub


extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css
